# render.yaml
services:
  - type: web
    name: sports-portal
    env: python
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: MONGO_URI
        sync: false